# Generated by Django 4.1.5 on 2023-01-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_Project_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task',
        ),
    ]
