# Generated by Django 4.1.5 on 2023-01-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_Project_App', '0002_rename_name_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-09-12'),
            preserve_default=False,
        ),
    ]
